### ISSUE TITLE
Reduce lot of unnecessary colors

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#3068]
- [ ] Rethink colors usage for icons in publication actions (like, comment, collect etc)

<sub>[ENG-13](https://linear.app/heyxyz/issue/ENG-13/reduce-lot-of-unnecessary-colors)</sub>

**Comment by foolo** [comment]
What do you think about using color themes? So instead of `<p classname="text-yellow-600">Important!</p>` you have something like `<p classname="text-alert-primary">Important!</p>`, and `text-alert-primary` would resolve to  a different color  depending on the current  theme, (light, dark, custom theme?). One obvious benefit would be that you, at least in theory, only would need to change the color in one place instead of hundreds.
