### ISSUE TITLE
Migrate entire web app to Next.js app directory

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#3867]
Migrate entire web app to Next.js app directory

<sub>[ENG-268](https://linear.app/heyxyz/issue/ENG-268)</sub>

**Comment by neo773** [comment]
@bigint Given the scope of the work could you assign this to me? don't want to result in duplicate work as it's common algora

**Comment by kunal00000** [comment]
Hi @neo773 , can I take this one up? You may be working on #3866 .

**Comment by neo773** [comment]
@kunal00000 Canceled my attempt for the cookie issue, feel free to work on it.

**Comment by neo773** [comment]
@tomalexing Hi there, yes, I'm actively working on it and have made good progress.

**Comment by alifalaksher** [comment]
@neo773 I'm not working on it.

**Comment by neo773** [comment]
@bigint 

Hi,

Just wanted to give you an update on the migration. Turns out, Lingui isn't compatible with the app directory and they don't plan on changing that. So, I've switched to [next-intl](https://github.com/amannn/next-intl), which is built to work with app directory.

I've managed to migrate most of the components with a codemod I wrote. The core layout and pages are also ported and the navigation is up and running.

However, I'm having some issues with the microservices. For some reason, they're not working on my machine, even after running the clean & bootstrap script twice. I keep getting an internal server error.

Because of this, I'm considering using mainnet. But, I'm currently on the waitlist to claim a handle. Is it possible for you to grant me early access? My wallet address is `0x433151dE147Af43aA1792326A813B73DAa15dCc7`.

**Comment by neo773** [comment]
@AliYar-Khan It's a WIP, I'm very close to wrapping it up.

**Comment by AliYar-Khan** [comment]
@neo773 no problem ... good luck !

**Comment by bigint** [comment]
@neo773 we removed lingui completely in lens-v2 branch which will be merged ASAP 🚀

**Comment by bigint** [comment]
For access you can still use testnet.hey.xyz to create account and use it

**Comment by shubh710** [comment]
@neo773 are you still working actively? let me know if you need help. I would be happy to help.

**Comment by AliYar-Khan** [comment]
@neo773 you haven't completed it yet ? let me know if you need a helping hand !

**Comment by neo773** [comment]
@AliYar-Khan 
I put my work in progress branch on hold as I waiting for `v2` to complete, will resume it soon.
Would've resulted in a huge merge conflict.

**Comment by bigint** [comment]
Thanks for the contribution @neo773, excited to see more from ya!!

**Comment by bigint** [comment]
@neo773 we are facing some issues now 😕 

<img width="323" alt="Screenshot 2023-11-21 at 11 28 04 PM" src="https://github.com/heyxyz/hey/assets/69431456/fe6cffbf-735a-4e97-b020-f5be773c3256">

titles are not rendering properly

also some pages are server rendered, example

/u/handle
/g/slug
/p/id


can you please look at it 🙇🏼 I can add tip for that!!

**Comment by bigint** [comment]
try run pnpm build, you can see lambda in that!

**Comment by neo773** [comment]
@bigint 
On it

**Comment by bigint** [comment]
thanks

**Comment by neo773** [comment]
@bigint 
Could we continue this on discord?

**Comment by bigint** [comment]
yup sure

**Comment by bigint** [comment]
what's ur discord? i can DM

**Comment by neo773** [comment]
neo773
