### ISSUE TITLE
Setting super follow not working

### ISSUE THREAD

**Issue by Riskafitria** [heyxyz/hey#3976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For setting disable/enable not working, please handle this is

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Others

**Comment by bigint** [comment]
Thank you for submitting this issue. However, it appears that the information provided is not sufficient for us to effectively understand and address your concern. Additionally, it seems that our standard issue template was not followed.

To help us better assist you, could you please update your issue to include the following:

1. A clear and concise description of what the issue is.
2. Steps to reproduce the behavior you're encountering.
3. Expected vs actual results.
4. Any relevant screenshots or logs.
5. Your environment details, like the version of the software and operating system.

Following the provided template helps us streamline the troubleshooting process and serve you better. Looking forward to your updated issue.
