### ISSUE TITLE
Still unable to post a message.

### ISSUE THREAD

**Issue by geoffzanelli** [heyxyz/hey#4031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot_2023-11-19-03-11-38-654-edit_com brave browser](https://github.com/heyxyz/hey/assets/66299707/0cd57ee1-4d94-4fd1-a8b8-bdc46da78ec9)

After clicking 'post,' there is no redirection to the wallet. When manually entering the wallet, a signature prompt appears. After confirming and returning to the browser page, it displays 'something went wrong,' and the posting feature remains unavailable.

### Expected Behavior

hope to resolve this issue; I haven't been able to use Lens for a long time.

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Brave

**Comment by bigint** [comment]
Thank you for submitting this issue. However, it appears that the information provided is not sufficient for us to effectively understand and address your concern. Additionally, it seems that our standard issue template was not followed.

To help us better assist you, could you please update your issue to include the following:

1. A clear and concise description of what the issue is.
2. Steps to reproduce the behavior you're encountering.
3. Expected vs actual results.
4. Any relevant screenshots or logs.
5. Your environment details, like the version of the software and operating system.

Following the provided template helps us streamline the troubleshooting process and serve you better. Looking forward to your updated issue.
