### ISSUE TITLE
i can’t post anything from my hey.xyz account 

### ISSUE THREAD

**Issue by gulbuke** [heyxyz/hey#4088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

it says posting but never posts and just CTA button become clickable again 

### Expected Behavior

i want to post when i click on the cta button

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Safari

**Comment by gulbuke** [comment]
![IMG_7858](https://github.com/heyxyz/hey/assets/55626944/2246672a-80ed-4d40-b204-2915b25fa106)

**Comment by gulbuke** [comment]
i want to be able to post asap:(

**Comment by bigint** [comment]
Thank you for submitting this issue. However, it appears that the information provided is not sufficient for us to effectively understand and address your concern. Additionally, it seems that our standard issue template was not followed.

To help us better assist you, could you please update your issue to include the following:

1. A clear and concise description of what the issue is.
2. Steps to reproduce the behavior you're encountering.
3. Expected vs actual results.
4. Any relevant screenshots or logs.
5. Your environment details, like the version of the software and operating system.

Following the provided template helps us streamline the troubleshooting process and serve you better. Looking forward to your updated issue.
