### ISSUE TITLE
Remove hard `location.reload` or hard navigate everywhere

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4182]
Make sure we clear all local cache while logging out!

This excludes `IndexStatus.tsx`

**Comment by neo773** [comment]
Can I get assigned?

**Comment by bigint** [comment]
@neo773 update the description 🙇🏼

**Comment by kesh-007** [comment]
Is the issue still open ?

**Comment by adevinwild** [comment]
Hi @bigint 👋

I'd like to try and tackle this task, it will be my first time on Hey project but I need more information so let's recap very quickly.

If I've understood the problem correctly, when I log out **the page has to reload in order to reset the cache.** (atm)

What you'd like is, instead of having a page that reloads, invalidate the client-side cache without having to reload the page, thus updating all the UI components.

For example, I'm on a post page and I've put a like with my profile
When I log out, the like should disappear BECAUSE I'm no longer logged in, so I'm back to the initial state.

Is this what you are looking for ?

**Comment by bigint** [comment]
exactly @adevinwild

**Comment by bigint** [comment]
@adevinwild you can create test account here https://testnet.tape.xyz/

**Comment by jayprakash25** [comment]
Can I work on this?

**Comment by adevinwild** [comment]
> Can I work on this?

I canceled my attempt on Algora 👍
Good luck, on my side it was impossible to get any replies on Discord from bigint/yoginth, I had one last point before finishing, you can take inspiration from what I did in the PR I think 🙌
