### ISSUE TITLE
Don't reload images or any assets on virtuosa items when scrolled and came back

### ISSUE THREAD

**Issue by bigint** [heyxyz/hey#4201]
https://github.com/heyxyz/hey/assets/69431456/dceccd17-4fd2-44de-98be-51045bae0d45

**Comment by rajdip-b** [comment]
/attempt #4201 can i be assigned this?

**Comment by bigint** [comment]
As said earlier FCFS based on PRs and it's quality

**Comment by rajdip-b** [comment]
> As said earlier FCFS based on PRs and it's quality

My attempts are stuck in validation or dependency :(

**Comment by bigint** [comment]
oops the video shows a protected endpoint, you can see any profile followers/following to reproduce it

**Comment by bigint** [comment]
https://github.com/heyxyz/hey/assets/69431456/ba108351-6547-49a1-abd7-844f5d77817b

**Comment by RutamBhagat** [comment]
https://github.com/heyxyz/hey/assets/72187009/86f865ff-197c-449d-ae4a-3aa15dbfcd6a

@bigint would this caching solution work? I am having some linting issues while creating a commit working on solving it
![image](https://github.com/heyxyz/hey/assets/72187009/dfa769d5-e63c-40e9-9399-03208d83fc9c)

**Comment by bigint** [comment]
We never wanna load the images again!

**Comment by tarunrajput** [comment]
@bigint, Is this not the concept of any virtual list? Elements are removed when not in view and will be re-rendered upon returning to the viewport.

**Comment by RutamBhagat** [comment]
yeah I think its similar to this thread https://github.com/petyosi/react-virtuoso/issues/298#issuecomment-946874723

**Comment by kriptonian1** [comment]
@bigint is this issue still up

**Comment by kriptonian1** [comment]
> We never wanna load the images again!

do you want to store it in cache or something

**Comment by chintanpuggalok** [comment]
@bigint is this still open?

**Comment by abhi12299** [comment]
@bigint what exactly is the issue? I see that the correct cache control headers are already added. The network requests in the browser are expected, because the virtual scrolling library actually mounts/unmounts react components, so the image requests will be there in the network tab, but as long as the Etag is the same, the request will be cached (provided the browser cache is enabled). Is this issue already fixed?

https://github.com/heyxyz/hey/assets/36722596/3d1ab9ab-70ea-4233-8201-4214a2d9f4a0
